language: node_js
node_js:
- '10'
sudo: enabled

install:
  - cd eth
  - npm install
  - npm install -g truffle
  - npm install -g ganache-cli@6.2.5

script:
  - ganache-cli -l 8000000 &> /dev/null &
  - truffle compile &> /dev/null &
  - truffle test --network development