language: node_js
node_js:
- '10'
sudo: enabled

install:
  - cd eth
  - npm install
  - npm install -g truffle
  - npm install -g ganache-cli

script:
  - ganache-cli -l 7000000 &> /dev/null &
  - truffle test --network development