language: node_js
node_js:
- '10'
sudo: enabled

install:
  - cd eth
  - npm install
  - npm install --dev
  - npm install -g truffle

script:
  - npx buidler compile &> /dev/null &
  - npx buidler test